// Generated by CoffeeScript 1.6.3
var $content, $d, $eventCard, $leftbar, eventCardDraggableOption, leftBar, leftBarDroppableOption;

$d = $(document);

$leftbar = $("#leftBar");

$content = $("#content");

$eventCard = $(".eventCard");

leftBar = {};

leftBar.defaultWidth = $leftbar.css("width");

leftBar.changeWidth = 50;

leftBar.expand = function() {
  return $leftbar.animate({
    "width": "+=" + leftBar.changeWidth + "px"
  });
};

leftBar.resetWidth = function() {
  return $leftbar.animate({
    "width": leftBar.defaultWidth
  });
};

leftBarDroppableOption = {
  over: function(event, ui) {
    return leftBar.expand();
  },
  out: function(event, ui) {
    return leftBar.resetWidth();
  },
  drop: function(event, ui) {
    return $content.append($("<h1>YOU SHOULD DO WORK HARD TO ACUTALLY MAKE IT WORK</h1>"));
  }
};

eventCardDraggableOption = {
  revert: true,
  cursor: true,
  cursorAt: {
    top: 10,
    left: 10
  },
  helper: function(event) {
    var outputSmallPicture, picHtml;
    $(this).animate({
      "opacity": 0
    }, 500);
    picHtml = $(this).children(".imgWrapper").html().toString();
    outputSmallPicture = picHtml.substr(0, picHtml.length - 1) + ' style="width: 50px;height: 50px;border-radius:50%">';
    return $(outputSmallPicture);
  },
  stop: function(event) {
    $(this).animate({
      "opacity": 1
    }, 500);
    return leftBar.resetWidth();
  }
};

$d.ready(function() {
  $leftbar.droppable(leftBarDroppableOption);
  return $eventCard.draggable(eventCardDraggableOption);
});
